image: os1ux/alpine-org2blog

before_script:
  - awk --version
  - emacs --version
  - pandoc --version

pages:
  script:
  - make requirements
  - make index
  - make blog
  - make stats_posts
  - make years
  - make image
  - make links
  - make markdown
  - make gemini
  - make publish
  - make sitemap
  - make htaccess
  - make tar_gz
  artifacts:
    paths:
    - public
  only:
  - master
