#+TITLE:       Resumen de JRRL3 en FISL12
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2011-07-03 22:19
#+HTML_HEAD:   <meta property="og:title" content="Resumen de JRRL3 en FISL12" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2011-07-03" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gomez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2011-07-03-jrrl3-fisl12.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


Recién pude terminar un resumen de lo que fueron las JRRL3 en el
[[http://softwarelivre.org/fisl12][FISL12]] todavía le faltan cosas,
especialmente transcribir varios videos, puedo agregar algunos
comentarios que se destacaron y lo bueno fue ver que luego de unos días
habíamos intercambiado ideas y el que inicialmente la dijo por primera
vez ahora estaba diciendo la idea de otro grupo y viceversa, realmente
compartimos un muy grata experiencia, seguro pudimos hacer algo más, en
la próxima jornada lo haremos o lo harán los que participen.

No publiqué antes porque quería contagiar el entusiasmo de lo vivido y
lo mucho que se hizo, por eso salen 9 videos, una pequeña selección de
fotos (saqué más de 200 por día) y al menos los títulos de cada una de
las charlas, para los que no pudieron ir, les aclaro que nos dieron todo
un track, un día completo de charlas dedicadas a
[[http://redeslibres.org/es/terceras-jornadas-regionales-de-redes-libres][JRRL3]]
en un gran auditorio, más un aula por 3hs otro día, la entrevista de
radio y una muy buena onda para sacarnos a pasear, llevarnos a almorzar,
cenar, bailar y compartir cerveza y amistad.

Creo que tenemos que aprovechar este impulso y contagiarlo a todos los
que alguna vez quisieron hacer algo y no se animaron, a todo aquél que
siente que es mucho trabajo, decirle que se puede, que tenemos que ser
más, de a poco iremos creciendo y mejorando, hay mucho por hacer y
contamos con personas extremadamente voluntariosas que van a dar una
mano.

El evento fue increíble, contar con la presencia de Elektra y
compartir conocimientos fue muy gratificante. Lamento que Lugro no
pudo estar para aprovechar un poco más la presencia de Elektra.

Charlamos varios pasos a seguir, por un lado queda trabajo por tener un
texto definitivo del Manifiesto, adaptado a cada idioma/región, por otro
lado usar OpenVPN/Tinc para interconectar todas las redes, aunque sea
sólo para ver que llegamos a otros nodos (aunque no sean funcionales los
enlaces) y para terminar, estaría bueno que
[[http://montevideolibre.org][MVDLibre]] y
[[http://buenosaireslibre.org][BAL]] vayan un fin de semana a Rosario y
armar una red híbrida entre [[http://olsr.org][OLSR]] y
[[https://secure.wikimedia.org/wikipedia/en/wiki/B.A.T.M.A.N.][BATMAN]],
charlamos al respecto con Elektra y coincidimos en que hay que
aprovechar los dos mundos.

Bueno, evidentemente mi poder de síntesis es bastante pobre, paso el
link:

[[file:jrrl3-terceras-jornadas-regionales-de-redes-libres-en-fisl12.org]]

Lo iré mejorando, se aceptan correcciones y si alguno se anima a hacer
subtítulos para los videos seria ideal, a cuantos más lleguemos mejor.

Un fuerte abrazo a todos! y la seguimos http://redeslibres.org, espero
poder viajar a Colombia para las cuartas jornadas!


** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/e46ec52748a7ecc60f09c3b95e363e92eaa0bebc][=2019-04-18 00:21=]] Agregar hora en header date
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5c8643b83930c6269569c76602608bd33f93008b][=2019-04-18 00:01=]] Corregir identación header #+INCLUDE:
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bbc3bbc728f2a3eeb4fe2e0a012ee5d8d613e3ef][=2015-07-03 04:31=]] @ 00:05 hs - elimino #+OPTIONS: de todos los archivos excepto header.org
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/74165280ffad770d1f8b8acbfa7f22b95459b52a][=2014-04-22 11:35=]] @ 00:34 hs - Agrego timestamp:nil
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5ad3755a3df07cdfbdc75d56cae06db2fee4b5f2][=2013-04-24 08:04=]] @ 01:50 hs - migro a org 8.0
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/652199f438b8e3b7f52720e2dc19208c9bcd7651][=2012-12-15 22:31=]] @ 04:00 hs - convert old blog in rST to org
