#+TITLE:       Free Software is cooperative
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2012-07-06 22:19
#+HTML_HEAD:   <meta property="og:title" content="Free Software is cooperative" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2012-07-06" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gomez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2012-07-06-free-software-is-cooperative.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


http://stories.coop/stories/written/free-software-cooperative

"A cooperative resolves the need to work in a democratic way, to reclaim
work as a creative enterprise, to build with others. Thus, work is not
simply done for profit maximization, but also for the growth of the
people who do it, taking into account the social and environmental
impact thereby generated," writes Pablo A. Vannini, a member of gcoop.

gcoop was formed by a group of young people who came together in 2005 to
form a cooperative to develop Free Software. We specialize in the
development of CRM Software (Client and Member Management), website
development (with Drupal technology), and customized development (using
Python and PHP).

Free Software has shown that collaborative and cooperative work
encourages the development of high quality information systems that
generate better solutions and adapt to the needs of clients. This idea
does not only apply to the activity of the cooperative, but goes to the
core of the enterprise - the development of a democratic organization
concerned with the development of the community in which it is located.

"A cooperative enterprise," Vannini explains "offers the only way for a
worker to be autonomous, responsible, and work in solidarity." He adds
that the cooperative form allows for mutual assistance and maintaining
the work even if someone falls ill or needs family leave. Working
together and helping each other creates a virtuous circle of growth.
"For us, the cooperative is not just a legal form, but also a movement
based on a rich history. The legal form is a starting point necessary
for securing the foundation of solidarity upon which to build the
project."

Other cooperatives of young programmers have been created based on the
experience of gcoop and together we have recently founded a Federation
specializing in the themes in which we work: Argentina Federation of
Worker Cooperatives for Technology, Innovation and Knowledge (FACTTIC
http://www.facttic.org.ar), based on the experience of the "Red Gráfica"
(http://www.redgraficacoop.com.ar/) and "Red Metalúrgica". gcoop is also
a member of the federation of workers cooperatives, FECOOTRA
(http://www.fecootra.org.ar).


** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/e46ec52748a7ecc60f09c3b95e363e92eaa0bebc][=2019-04-18 00:21=]] Agregar hora en header date
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5c8643b83930c6269569c76602608bd33f93008b][=2019-04-18 00:01=]] Corregir identación header #+INCLUDE:
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bbc3bbc728f2a3eeb4fe2e0a012ee5d8d613e3ef][=2015-07-03 04:31=]] @ 00:05 hs - elimino #+OPTIONS: de todos los archivos excepto header.org
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/74165280ffad770d1f8b8acbfa7f22b95459b52a][=2014-04-22 11:35=]] @ 00:34 hs - Agrego timestamp:nil
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5ad3755a3df07cdfbdc75d56cae06db2fee4b5f2][=2013-04-24 08:04=]] @ 01:50 hs - migro a org 8.0
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/00977674c60135495c431e80cae66c249d08aa42][=2012-12-16 09:50=]] @ 00:43 hs - Corrijo formato archivos.
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/652199f438b8e3b7f52720e2dc19208c9bcd7651][=2012-12-15 22:31=]] @ 04:00 hs - convert old blog in rST to org
