#+TITLE:       Carta Abierta Software Libre con CFK
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2012-05-24 22:19
#+HTML_HEAD:   <meta property="og:title" content="Carta Abierta Software Libre con CFK" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2012-05-24" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gomez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2012-05-24-carta-abierta-software-libre-con-cfk.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


:url: http://www.softwarelibreconcfk.com.ar/carta-abierta-24-05-2012

Buenos Aires, 24 de Mayo de 2012

Compañera Presidenta:

Ayer nos enteramos a través de los medios de comunicación [fn:1] que
la empresa Microsoft presentó ante usted un plan de "desarrollo
sustentable". Desde nuestra joven organización: "Software Libre con
CFK" leímos con mucho pesar los detalles de la reunión que mantuvo con
Brian Kevin Turner, Director de operaciones de la compañía.

Entendemos que desde el 25 de Mayo de 2003 vivimos un proceso de
transformación, donde la profundización de nuestra soberanía y la
lucha contra los monopolios de la comunicación han sido ejes centrales
de este proyecto nacional y popular.

El Software Libre va exactamente en la misma dirección que esas
políticas tan valientemente implementadas primero por el compañero
Néstor Kirchner y luego por Usted, ya que nos da la posibilidad de
obtener la soberanía tecnológica necesaria para encarar este período
de desarrollo nacional. Adicionalmente, evita la proliferación de
monopolios, tan nocivos para nuestra sociedad, y permite ejercer
soberanamente el derecho a la información no siendo simples
consumidores sino productores de tecnología. Todo esto no es posible
con el Software Privativo que promueve Microsoft.

Desde hace más de 30 años, esta empresa, forjó el monopolio más
importante del planeta. Hoy más del 90% de las computadoras utilizan
Windows, el Sistema Operativo de ésta corporación. Esto implica no
sólo un poder simbólico, sino también material.

La época que estamos viviendo nos muestra que el camino a recorrer es
de la mano de los diferentes pueblos de América Latina consiguiendo,
todos juntos, la independencia tecnológica que nos permita continuar
desarrollándonos. Por citar tan sólo algunos ejemplos, los Presidentes
Rafael Correa [fn:2], Hugo Chavez [fn:3] y el ex Presidente Lula Da
Silva [fn:4] ya han comenzado este camino debido a que entendieron que
el desarrollo de sus pueblos no podrá darse si permiten que sean los
monopolios transnacionales los que controlen las tecnologías. Es por
tal motivo que no han dejado lugar a dudas: En Ecuador, Venezuela y
Brasil, la implementación de Software Libre es política de Estado.

En Argentina ya son dos las provincias que consideran política pública
el Software Libre, y así lo expresaron con sus leyes: Río Negro y
Santa Fe. Sin embargo, creemos que es fundamental que desde el Estado
Nacional se considere una Ley de Software Libre que haga su
contribución al proyecto nacional y popular, en pos de la soberanía
tecnológica.

Atravesamos un período donde es fundamental seguir profundizando la
sustitución de importaciones. En el ámbito privado nacional existen
cooperativas de trabajo [fn:5] y pymes [fn:6] que generan trabajo de
alto valor agregado. Lo opuesto ocurre con empresas de tecnología
extranjeras ya que el trabajo que generan en el país es residual y se
limita a la venta en dólares de licencias de software.

Querida Presidenta, hemos recorrido un largo camino, y aún nos quedan
muchas más batallas que dar. La Ley de Servicios de Comunicación
Audiovisual y el Programa Conectar Igualdad, son ejemplos inmejorables
de lo importante que es democratizar la palabra y el acceso y la
participación en materia de comunicación.

Estamos seguros de que nuestro pueblo puede ser artífice de su propio
destino. El Software Privativo es una piedra en ese camino.

Quedamos a su disposición para reunirnos con usted y charlar en
profundidad estos temas que consideramos fundamentales.

La saludamos muy atentamente, renovando nuestro compromiso y lealtad a
su conducción

Software Libre con CFK.

[fn:1] http://www.telam.com.ar/nota/26206/
[fn:2] http://www.youtube.com/watch?v=Hy5yAk4dYOk
[fn:3] http://www.youtube.com/watch?v=c8bRKoi4riU
[fn:4] http://www.youtube.com/watch?v=6Rwvy0PN3b8
[fn:5] http://www.facttic.org.ar/
[fn:6] http://www.cadesol.org.ar/

** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/e46ec52748a7ecc60f09c3b95e363e92eaa0bebc][=2019-04-18 00:21=]] Agregar hora en header date
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5c8643b83930c6269569c76602608bd33f93008b][=2019-04-18 00:01=]] Corregir identación header #+INCLUDE:
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bbc3bbc728f2a3eeb4fe2e0a012ee5d8d613e3ef][=2015-07-03 04:31=]] @ 00:05 hs - elimino #+OPTIONS: de todos los archivos excepto header.org
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/74165280ffad770d1f8b8acbfa7f22b95459b52a][=2014-04-22 11:35=]] @ 00:34 hs - Agrego timestamp:nil
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/5ad3755a3df07cdfbdc75d56cae06db2fee4b5f2][=2013-04-24 08:04=]] @ 01:50 hs - migro a org 8.0
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/e4dc30e2a202e7ad44bddc761065e9aeb0a31bd3][=2013-03-21 02:27=]] @ 01:58 hs - agrego cambios según git.osiux.com
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/652199f438b8e3b7f52720e2dc19208c9bcd7651][=2012-12-15 22:31=]] @ 04:00 hs - convert old blog in rST to org
