#+TITLE:       Percona Live 17 =day three= keynotes
#+AUTHOR:      Osiris Alejandro Gómez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2017-04-27 03:43
#+HTML_HEAD:   <meta property="og:title" content="Percona Live 17 =day three= keynotes" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2017-04-27" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gómez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2017-04-27-percona-live-17-day-three.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


#+INCLUDE: "2017-04-23-percona-live-17-header.org"

** Day Three

   La manaña nuevamente comenzó con los keynotes, Paul Dix de Influx
   hablo sobre los posibles modelos para tener una emrpesa
   Open-source, desde su perspectiva, (justo ayer hablamos sobre la
   dificultad de entender el software libre sin un modelo de negocios,
   a el le sorprendía que el de SQLite viviera solo haciendo
   consultorías ya que su aplicación esta en el dominio publico) y si
   bien su vision era extremadamente comercial pensando en lograr una
   gran empresa y ganar mucho dinero, hablo de que redhat es lo más
   parecido a la mafia y que hay empresas que se dedican a vampirizar
   productos open-source (palo para Percona), estuvo buena y según el
   veía, estaba la posibilidad de trabajar en un core (y liberarlo) y
   luego vender plugins, extensiones, etc.

*** Consultoría

*** Oracle

    Hablaron de lo nuevo de MySQL 5.8

*** charla inspiradora

    Fue la de *Aaron Schwartz*, que habló sobre para que lado va el
    mundo.

    - Observavilidad
    - Velocidad
    - Distribuido

*** el cierre

    Un Panel moderador por Richard Hipp (SQLite) en el que participaron
    Peter Zaisev, Baron Schwartz y MC Brown

    - las TSDB (Time Series Databases) son realmente algo nuevo? deben
      ser un nuevo motor o pueden ser extensiones de motores actuales

    - que esperamos del mundo de las DBs en 2020

    - las nuevas generaciones de programadores no saben SQL y que hoy ha
      varias herramientas que con sus diferentes abstraciones permiten
      generar SQL sin entenderlo y que obviamente no existe un solo
      standard de SQL y que si bien era muy importante entederlo y poder
      escribir quieries eficientes, en el futuro cada vez menos
      developers van a entender SQL, aunque tambien pareceria ser
      cultural porque hay leguajes como LINQ que es un SQL dentro del
      codigo .net para el manejo de objetos y que si preguntas en una
      conferencia de MS todos los Developers lo usan

      https://www.percona.com/live/17/sessions/keynote-panel-percona-vividcortex-continuent

*** keynotes

*** Chau Percona

    El cierre fue un poco abrupto para mi, aunque como indicaba el
    cronograma, a las 16 terminban las charlas y a las 16:15 era la
    entrega de premios, ni bien terminó la entrega de premios dijeron,
    chau y todo termino exactamente a las 16:30 hs, aunque intenté
    alargar un poco yendo al bar del hotel y clavarme un percona punch
    por solo 6 USD (mas impuestos) la mayoría ya se tomaba el palo. :(

    Asi que aproveche para ir a un Target y comprar regalos para mi
    familia :)

** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/e46ec52748a7ecc60f09c3b95e363e92eaa0bebc][=2019-04-18 00:21=]] Agregar hora en header date
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/682f3f0adff5b9ddfc40d3f0eba5b8ebb2f13128][=2019-04-09 19:37=]] Actualizar archivos para exportar a html utiliznado publish.el
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/882b1cda084f7c18362c8414a78dd65c7b968a3f][=2019-04-09 03:01=]] Recuperar archivos en .md y convertirlos a .org
