#+TITLE:       quién necesita mas de 64 redes WiFi cerca? 
#+DESCRIPTION: iwlist Failed to read scan data : Argument list too long
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2021-03-09 23:36

** a veces la /WiFi/ no me anda

Hace tiempo que /"a veces"/ la /WiFi/ de no me responde y no ve ninguna
red, pensaba que tenía que ver con el suspender, porque generalmente
sucedía cuando volvía de una suspensión, pero /"a veces"/ también pasaba
al moverme de lugar e intentar cambiar de /AP/ (si, tengo varios /APs/ en
casa), a veces se _solucionaba_ reiniciando...

** encontrando el =error=

Luego de probar varias /giladas/ de costumbre y monitorear los /logs/,
matar la /WiFi/ con =rfkill= vi el error /=Failed to read scan data :
Argument list too long=/ al utilizar =iwlist wlan0 scan=, un par de
veces hasta que devolvió el listado y me pude conectar...

** el /bug/ no es nuestro

Me puse a buscar si había un /bug/, a alguien más le tenía que pasar
esto mismo y obvio existe el /=bug 900742=/ [fn:debian900742] en
/Debian/ y dice /won't fix/, onda no somos nosotros, es el =kernel= o
=wicd= y leyendo terminé en el /=bug 1801751=/ [fn:wicd1801751] de
=wicd= donde dicen /no somos nosotros/, son las =wireless-tools= pero lo
mas interesante es que acá descubrieron el error del /"a veces"/ y es
**super específica la condición de error**:

/="no wireless networks found" if >64 networks=/

** hay demasiadas redes!

Cuando empezó este síntoma, usaba =cachaza= (mi /notebook/ anterior) y
cuando logré conectarme habían =53= redes y cuando no lograba
evidentemente eran más y en un momento llegué a detectar =86= redes
cercanas... con la antena de la /notebook/!

Importante, descubrí que el error sucede solo con =iwlist wlan0 scan= y
no pasa con =iw wlan0 scan=.

Hoy día me sucede lo mismo con /=tequila=/ [fn:thinkpadbuster], al punto
de detectar =330= redes con la antena de la /notebook/ y sin contar mis
/APs/.

Tengo que ver, seguramente podré ajustar la sensibilidad para que
detecte menos redes... =:P=

De momento cuando se complica, encontré una solución analógica, utilizar
algo metálico para cubrir para de la /notebook/ reduce la cantidad de
redes detectadas :)

** /ranking/ de redes

Hago un breve /ranking/ de /SSIDs/ para ilustrar el vecindario:

#+BEGIN_SRC sh :exports code

grep SSID wlan0-1614375901.log | cut -d: -f2 | awk '{print $1}'  | tr A-Z a-z | cut -d- -f1 | tr -d '+.' | sort | uniq -c | sort -nr | barra

 51.69 %  51.69 %        168 |||||||||||||        telecentro 
 82.15 %  30.46 %         99 |||||||              fibertel 
 83.38 %   1.23 %          4 |                    sc 
 84.31 %   0.92 %          3 |                    wifi 
 84.92 %   0.62 %          2 |                    wysz 
 85.54 %   0.62 %          2 |                    natalia 
 86.15 %   0.62 %          2 |                    monicanora 
 86.77 %   0.62 %          2 |                    mishka 
 87.38 %   0.62 %          2 |                    lopez 
 88.00 %   0.62 %          2 |                    iris 
 88.62 %   0.62 %          2 |                    huma 
 89.23 %   0.62 %          2 |                    fz21 
 89.85 %   0.62 %          2 |                    ferro 
 90.46 %   0.62 %          2 |                    chefgonzi 
 91.08 %   0.62 %          2 |                    arapere 
 91.38 %   0.31 %          1 |                    speedy 
 91.69 %   0.31 %          1 |                    sonr\xc3\xada 
 92.00 %   0.31 %          1 |                    skynet 
 92.31 %   0.31 %          1 |                    shibolet 
 92.62 %   0.31 %          1 |                    rosana12! 
 92.92 %   0.31 %          1 |                    river5,8 
 93.23 %   0.31 %          1 |                    river 
 93.54 %   0.31 %          1 |                    *red 
 93.85 %   0.31 %          1 |                    paula 
 94.15 %   0.31 %          1 |                    olga 
 94.46 %   0.31 %          1 |                    nora 
 94.77 %   0.31 %          1 |                    mercurio 
 95.08 %   0.31 %          1 |                    matan 
 95.38 %   0.31 %          1 |                    lisandro24 
 95.69 %   0.31 %          1 |                    lilianmg6042 
 96.00 %   0.31 %          1 |                    hernan_5 
 96.31 %   0.31 %          1 |                    franco 
 96.62 %   0.31 %          1 |                    fibertel_prov 
 96.92 %   0.31 %          1 |                    fibertei 
 97.23 %   0.31 %          1 |                    fiberel 
 97.54 %   0.31 %          1 |                    fausto 
 97.85 %   0.31 %          1 |                    colgatedesta5g 
 98.15 %   0.31 %          1 |                    charitoo 
 98.46 %   0.31 %          1 |                    carolina 
 98.77 %   0.31 %          1 |                    bruss2 
 99.08 %   0.31 %          1 |                    bruss 
 99.38 %   0.31 %          1 |                    birds 
 99.69 %   0.31 %          1 |                    azulgrana55 
100.00 %   0.31 %          1 |                    alan_ibarra90 

#+END_SRC

** juntando datos

Voy a tener que actualizar mi /=grafo de redes=/ [fn:graforedes] a ver
cuantas veo con una antena grillada de 21dbi en la terraza. =;)=

Por ahora dejé un =cron= que detecta y guarda las redes detectadas para
hacer algun análisis a futuro.


[fn:debian900742]   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900742
[fn:wicd1801751]    https://bugs.launchpad.net/wicd/+bug/1801751
[fn:thinkpadbuster] https://osiux.com/2021-02-09-install-debian-buster-on-thinkpad-t14-gen-1.html
[fn:graforedes]     https://osiux.com/2012-03-05-redes-abiertas-versus-redes-cerradas.html
