#+TITLE:       /Hablar, escribir, pensar: el software no es un trabajo de escritorio/
#+AUTHOR:      Daniel Fone
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2021-03-24 22:31


En la b칰squeda permanente de mejorar mis /skills/ encontr칠 este
excelente /post/ de /Daniel Fone/ y comparto una mala traducci칩n =:P=

* Hablar, escribir, pensar: el software no es un trabajo de escritorio

- Fuente: https://daniel.fone.net.nz/blog/2020/10/21/talking-typing-thinking-software-is-not-a-desk-job/

Octubre de 2020 췅 aproximadamente 7 minutos para leer

=tl;dr= Los desarrolladores optimizan demasiado la ergonom칤a de la
mecanograf칤a y no lo suficiente para la ergonom칤a del pensamiento.

Tuve una ducha maravillosa el otro d칤a.

Era tarde en la ma침ana (como suelen ser las mejores duchas) y estaba
reflexionando sobre c칩mo paso mi tiempo durante el d칤a. Como consultor
que trabaja desde casa, constantemente necesito justificar mi
facturaci칩n y mi tiempo, y en este caso estaba justificando gastar m치s
en la ducha.

Como la mayor칤a de nosotros, comenc칠 mi carrera con la impresi칩n de que
pas칠 un d칤a productivo ergon칩micamente equilibrado sobre un teclado
escribiendo cientos de l칤neas de c칩digo en /Microsoft Visual Basic 6.0
Professional Edition/, y no parado en una corriente perfectamente
caliente de agua dulce a alta presi칩n. Sin embargo, cuanto m치s tiempo
paso como desarrollador, menos estoy convencido de que necesito estar en
mi escritorio para entregar el valor comercial verdaderamente asombroso
de la hoja de c치lculo a la aplicaci칩n web que brindamos los consultores
de ingenier칤a senior.

Para que usted tambi칠n pueda justificar pasar la mayor parte de la
ma침ana envuelto en un capullo de calidez limpiadora, analicemos esto y
veamos 5 actividades f칤sicas del desarrollo de software eficaz. Como
todas las listas buenas, esto est치 ordenado aproximadamente en orden
creciente de tiempo e importancia.

** 5. Hablar

Algunos desarrollos de software probablemente no necesitan hablar para
ser efectivos. Entiendo, por ejemplo, que se considera universalmente de
mala educaci칩n hablar en voz alta sobre el desarrollo del /kernel/ de
/Linux/. El contenido de =~/bin= tambi칠n, no hablamos.

Pero cada proyecto comercial en el que he trabajado ha necesitado al
menos una charla. Cuando las personas est치n demasiado ocupadas o son
demasiado t칤midas para hablar, la falta de comunicaci칩n de gran ancho de
banda puede dificultar la identificaci칩n de los requisitos y la
descomposici칩n de los problemas comerciales mal explicados.

Pero lo que es m치s importante, la falta de conversaci칩n dificulta la
creaci칩n de confianza y comunicaci칩n, algo fundamental en las primeras
etapas de cualquier nueva relaci칩n. Como animales sociales, somos
particularmente buenos para hacer esto verbalmente, y no particularmente
buenos para hacerlo con correos electr칩nicos y /subtweets/ picantes.

Por otro lado, he trabajado en proyectos donde hablar es un apoyo para
disfrazar que nadie sabe qu칠 hacer. Donde una docena de personas se
sientan en una habitaci칩n y hablan durante una hora sin decir nada y
todos salimos m치s tontos que cuando entramos.

Entonces, para la mayor칤a de los casos: hablar es fundamental, pero en
la cantidad correcta.

** 4. Escuchar

Honestamente, solo inclu칤 esto por simetr칤a. Lo 칰nico que agregar칠 es
que tenemos dos o칤dos y una boca, por lo que la audici칩n binaural ofrece
una ventaja evolutiva contra cierta presi칩n de selecci칩n o se supone que
debemos escuchar el doble de lo que hablamos.

Toma tu sabidur칤a concisa como quieras.

(busca r치pidamente en /Google/ por qu칠 tenemos dos orejas)

** 3. Escritura

춰Escribiendo c칩digo por supuesto! Pero tambi칠n ... =READMEs=,
comentarios, documentaci칩n en l칤nea, descripciones de relaciones
p칰blicas, revisiones de c칩digo, =git commits=; todo esto es parte del
trabajo principal. Es tentador ver esta metaescritura como una
sobrecarga adem치s de la escritura de "c칩digo" real. Pero la escritura
efectiva en estos otros lugares es un multiplicador de fuerza para su
c칩digo.

Sin embargo, lo que es mucho m치s importante, en mi experiencia, la mejor
comunicaci칩n est치 escrita.

- Es asincr칩nico, lo que significa que se puede consumir cuando sea
  conveniente para cada lector (es decir, despu칠s de una ducha
  matutina).

- Se puede distribuir f치cilmente y no tiene p칠rdida de fidelidad
  cuando se comparte (en comparaci칩n con hablar con /John/ sobre lo que
  /Sarah/ le dijo que /Steve/ dijo en la reuni칩n en la que ninguno de
  ustedes estuvo).

- Crea un registro, en lugar de "espera, 쯣or qu칠 hicimos ...?"

- /=춰Escribir es pensar!=/ [fn:writeisthinking] Escribir te obliga a
  estructurar tus ideas de manera coherente (al menos, lo parece para
  algunas personas). Revela deficiencias o lagunas en su comprensi칩n o
  plan.

Debido a esto, animo a que las comunicaciones del equipo se escriban en
su mayor칤a. /Jira/, /Slack/, correos electr칩nicos, /trello/,
publicaciones de /blog/, lo que sea. Incluso una foto en alta resoluci칩n
de una pared de notas /post-it/ ha sido en ocasiones una hoja de ruta
arquitect칩nica indispensable. Independientemente de c칩mo se publique, la
redacci칩n detallada y bien pensada es 游눮.

Quiz치s incluso m치s importante que escribir es ...

** 2. Lectura

Habiendo ensalzado las virtudes de escribir =READMEs=, enviar mensajes,
descripciones de relaciones p칰blicas, etc., obviamente deber칤a animarle
a leerlos. Se llama =README= EN MAY칔SCULAS por una raz칩n, y no solo
porque sea un acr칩nimo. Sin embargo, si tuviera un d칩lar por cada vez
que alguien me hiciera una pregunta que ya fue respondida en el
=README=, tendr칤a tres d칩lares. 游눯

Esto se debe a lo que yo llamo sucintamente el ciclo
vicioso-lectura-escritura-retroalimentaci칩n. Cuando la gente no
actualiza el comentario, la gente se capacita para ignorarlo, por lo que
la gente no lo actualiza, etc. A decir verdad, si sabes que alguien est치
leyendo tus =git commits=, su calidad mejorar치 r치pidamente. Incluso si
nunca antes ha le칤do un compromiso de /Git/ coherente de sus colegas,
nunca es demasiado tarde para pedirles que expliquen lo que finalmente
significa arreglarlo.

Pero al igual que la escritura, el valor de la lectura se extiende mucho
m치s all치 del dep칩sito de c칩digo.

Recientemente comenc칠 un proyecto que involucraba un campo completamente
desconocido de la tecnolog칤a m칠dica
(ps, /=todav칤a eres mi paciente favorito=/ [fn:stillfavourite]
01-004 游늵仇벒잺). La actividad m치s valiosa que encuentro en esta
etapa de un proyecto es leer.

Tenemos que analizar un formato de
/=archivo especializado=/ [fn:eudataformat], para el cual hay
/=una gema=/ [fn:gem]. Pero, 쯣or qu칠 dejar todo ese contexto 칰til
enterrado dentro de la gema?
La /=especificaci칩n del archivo=/ [fn:edf] no es tan larga, incluso si
se necesitan muchos intentos para comprenderla. Leer la especificaci칩n
del formato de archivo hace que sea mucho m치s f치cil entender por qu칠 la
/gema/ necesita /=load_digital_signals_by_epoch=/ [fn:digsigepoch], lo
que a su vez sugiere soluciones alternativas al problema que tiene entre
manos.

Ninguno de los posibles adyacentes se puede descubrir sin los
conocimientos adquiridos al leer estas fuentes, as칤 que sea lo que sea
con lo que est칠 tratando, vaya a la fuente y lea, lea, lea ...

- documentaci칩n (leer el /=manual de postgres=/ [fn:postgresql] muy bien
  escrito o los /=documentos de Redis=/ [fn:redis] es la experiencia m치s
  칤ntima que tuve con /Neo/ descargando /kung-fu/ en su cerebro)

- c칩digo (muy subestimado: no hay una /gema/ en mis archivos /Gem/ que
  no haya agrupado al menos una vez)

- archivos de registro (/log files/), mensajes de error, ese tutorial
  sobre c칩mo leer gr치ficos de llamas

- la especificaci칩n, la legislaci칩n, el documento de pol칤tica, la
  directriz del /NIST/, el art칤culo original en /open access journal/.

... ya captas la idea, solo encuentra el documento autorizado y
sorpr칠ndelo en tu cerebro. Incluso si parece que nada se pega, un breve
encuentro con el texto dejar치 una impresi칩n duradera. Es como la
homeopat칤a pero real.

Hablar / escuchar ... escribir / leer ... y finalmente ... ruidos de
redoble de tambores

** 1. Pensando

Cuando lo reduce, este es el esfuerzo principal para m칤 y, sin embargo,
es algo oculto.

쮺u치nto de mi tiempo de programaci칩n / codificaci칩n / desarrollo se
dedica a pensar en los problemas? Modelar el dominio, pensar en los
casos extremos, jugar mentalmente con abstracciones.

Y es obvio cuando piensas en lo que hace buenos desarrolladores. Las
personas con las que m치s valoro trabajar no son mecan칩grafos precisos,
son pensadores claros.

Sin embargo, persiste la imagen de que escribir es funcionar y trabajar
es escribir y un d칤a productivo es en su silla en su escritorio. As칤 que
tenemos monitores duales de 4k, teclados mec치nicos, sillas /aeron/,
barra t치ctil, atajos de =vim=, lo que sea que nos optimice al hacer
tapping en nuestras computadoras.

Pero, 쯖u치nta atenci칩n prestamos a la ergonom칤a del pensamiento?

Cuando elevamos el "pensamiento" al trabajo principal, naturalmente
comenzamos a optimizarlo espec칤ficamente. En general, no necesitamos
estar frente a nada para pensar con eficacia y, a menudo, creo que es
mejor no estarlo. Mis momentos de mayor claridad son invariablemente
cuando me muevo, a menudo cuando hago ejercicio. Adem치s, puedo leer en
mi tel칠fono pr치cticamente en cualquier lugar, y las mejores
conversaciones se mantienen a menudo mientras paseo.

Entonces, aunque estoy contento por toda la ergonom칤a de mi espacio de
trabajo, cada vez m치s encuentro que escribir c칩digo es la parte breve en
la que simplemente estoy cosechando toda la cosecha mental que he
sembrado de hablar, escuchar, leer y pensar.

Para resumir esto en algo un poco m치s aliterativo, a veces lo he
descrito como las 3 /Ts/ (/talking typing thinking/) del desarrollo de
software ...

** Hablar 췅 Tipear 췅 Pensar

*Hablar* y escuchar; las discusiones verbales. La mayor칤a de las veces
necesitamos una cantidad peque침a pero cr칤tica de comunicaciones
s칤ncronas de gran ancho de banda.

*Escribir* comentario de c칩digo: =READMEs=, revisiones de c칩digo,
descripciones de relaciones p칰blicas; y toda la comunicaci칩n
asincr칩nica: actualizaciones del proyecto, descripciones t칠cnicas,
correos electr칩nicos con los pr칩ximos pasos; Todos estos son una parte
esencial del trabajo y no solo un trabajo auxiliar o ajetreado. Tambi칠n
escribiendo c칩digo real en alg칰n momento. Pero encuentro que cuanto m치s
tiempo pasas escribiendo las otras cosas, menos tiempo necesitas dedicar
(re) escribir c칩digo.

*Pensamiento*: (incluido, a efectos de aliteraci칩n, lectura)

Hablar, escribir, pensar: este es el trabajo que hacemos. Y yo, por mi
parte, quiero darme el espacio para hacer todas las partes realmente
bien.

De todos modos, tengo que ir a darme una ducha. 游

** Te recomiendo leer

- [[file:2021-03-22-remote-async-communication.org][/=La Comunicaci칩n Asincr칩nica es un Superpoder para el Trabajo Remoto=/]]

[fn:writeisthinking]  https://alistapart.com/article/writing-is-thinking/
[fn:stillfavourite]   https://twitter.com/danielfone/status/1318026784454045703
[fn:eudataformat]     https://en.wikipedia.org/wiki/European_Data_Format
[fn:gem]              https://github.com/nsrr/edfize
[fn:edf]              https://www.edfplus.info/specs/edf.html
[fn:digsigepoch]      https://github.com/nsrr/edfize/blob/93566cdc82b160ef319c51908c1c4a19666e2625/lib/edfize/edf.rb#L243
[fn:postgresql]       https://www.postgresql.org/docs/current/index.html
[fn:redis]            https://redis.io/documentation


** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/49b23dcf61daf60f2bc81f7b0901b57a800e679f][=2021-03-24 23:21=]] corregir formato /link footnote/
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/a533fb86ad5ebda931a19ec321bba90dad633b3b][=2021-03-24 23:19=]] agregar traducci칩n de /talking - typing - thinking/
