#+TITLE:       Cooperativismo y Software Libre
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2021-03-01 22:22


** discusión recurrente

Cada tanto, en /=gcoop=/ [fn:gcoop] como en cualquier otra organización,
volvemos a debatir temas recurrentes y hace un tiempo reflotó una
discusión que esta ampliamente cubierta por otras organizaciones
similares en el libro /*Saberes Recuperados*/ y me alegra que fue leído
y lo recuerden, pero no puedo dejar de mencionar que no es algo que esta
ahí dando vueltas por que si, fue lectura recomendada en varias
oportunidades desde/en /gcoop/ en capacitaciones, reuniones de
planificación, como respuesta institucional a otras cooperativas.

** profundizar lo charlado

Desde que ingresé a /gcoop/, cada /link/, dato, recomendación propuesta
por los socios que la fundaron, para mi fue una obligación implícita a
leer y profundizar lo charlado, esto se complementó a lo largo de los
años con las visitas y eventos a/en otras cooperativas y nutriendo de
cada otra actividad de esas que siempre nos invitan, generamos o nos
involucramos y creo que desde hace un par de años (mi percepción) asumir
que al compartir un par de /links/ luego de una charla o capacitación no
significa que vayan a ser leídos y en algunos casos (tristemente) ni
siquiera recordados.

** base común

Tenemos una vida más allá del trabajo y el tiempo es finito, pero
tampoco podemos completar esta investigación en profundidad
exclusivamente en el horario laboral, en mi caso este tipo de lecturas
las hice viajando en /bondi/ o /subte/, a veces en fin de semanas e
incluso vacaciones... porque contar con una base en común de textos,
permite sentarnos a discutir y/o profundizar sin partir de cero.

** listado a completar

A la espera de que este /post/ este siempre disponible y con suerte un
poco mas visible, voy a ir detallando un listado de /links/ a textos que
considero importantes leer para entender un poco más sobre
/*Cooperativismo y Software Libre*/ para quien quiera adentrarse en este
mundo alternativo.

- /=Mini resumen licencias=/ [fn:licencias]
- /=La catedral y el bazaar=/ [fn:catedral]
- /=Richard Stallman: Qué es el Software Libre=/ [fn:rms-sl]
- /=En el principio fue la línea de comandos=/ [fn:comandos]
- /=La ética del hacker=/ [fn:pekka]
- /=Hackers y Pintores=/ [fn:pintores]
- /=Cooperativismo de plataforma=/ [fn:plataformas]
- /=Saberes Recuperados=/ [fn:saberes] 

[fn:gcoop]       https://www.gcoop.coop/
[fn:licencias]   https://osiux.com/introduccion-al-software-libre.html
[fn:rms-sl]      https://endefensadelsl.org/que_es_el_software_libre.html
[fn:plataformas] https://endefensadelsl.org/cooperativismo_de_plataforma.html
[fn:catedral]    http://biblioweb.sindominio.net/telematica/catedral.html
[fn:comandos]    http://biblioweb.sindominio.net/telematica/command_es/command_es.pdf
[fn:pekka]       http://eprints.rclis.org/12851/1/pekka.pdf
[fn:pintores]    http://www.paulgraham.es/ensayos/hackers-y-pintores.html
[fn:saberes]     http://empresasrecuperadas.org/Saberes-Recuperados-Completo.pdf
