#+TITLE:       /Vivir del Software Libre/
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2021-02-16 10:28


** /y si fundamos una cooperativa?/

Un día como hoy (=16/FEB/2007=), hace =14 años=, =6 militantes= del
/Software Libre/ decidieron fundar una /Cooperativa de Software Libre/
porque conocían la autogestión de los =LUGs= [fn:lugs] /=Linux Users
Groups=/ para organizar grandes eventos como =CaFeCONF= [fn:cafeconf]
/=Conferencia Anual de CaFeLUG=/ o =JRSL= [fn:jrsl] /=Jornadas
Regionales de Software Libre=/, donde ademas de charlas técnicas se
difundían las /=libertades del Software Libre=/ [fn:libertades].

Organizar grandes eventos es una cosa y /vivir del Software Libre/ es
otra, estuvieron dando vueltas al dilema de /"no tenemos trabajo porque
no tenemos papeles y no tenemos papeles porque no tenemos trabajo"/, y
para arrancar de una vez, decidieron hacer los trámites y formalizarse
en /=Cooperativa de Trabajo gcoop Ltda.=/ [fn:gcoop] y de esta manera
comenzaron a trabajar desde un pequeño departamento en el barrio de
Almagro.

** /no hay libertad sin sacrificio/

Yo llegué a =gcoop= en Agosto, 6 meses después de su fundación y solo
quedaban 2 de sus fundadores, por diferentes motivos, 4 de ellos se
alejaron del proyecto.

Un mes después, en Septiembre, se sumaron 2 nuevos socios (militantes de
=CaFeLUG= [fn:cafelug]), y no fue nada fácil empezar a desarrollar e
integrar nuestro primer =CRM= [fn:crm] para el
/*Centro de Atención de Usuarios*/ [fn:atusu] del
/*Banco Credicoop Cooperativo Limitado*/ [fn:bccl], en ese momento no lo
sabíamos, pero fue el puntapié inicial para muchísimos desarrollos
posteriores como =GCA= [fn:gca] /=Gestión de Contacto con el Asociado=/,
pero lo que sí sabíamos es que /*teníamos que crecer*/.

** especialistas en /CRM/

Sin dudas, desde el comienzo nos especializamos en /CRM/ y al día de hoy
contamos con "la implementación mas grande de /=SuiteCRM=/ [fn:suitecrm]
en Latinoamérica" y fue todo un desafío desarrollar al principio con
/=SugarCRM=/ para luego migrar a /=SuiteCRM=/ y esa historia esta muy
bien resumida en el hilo de /twitter/ de /=Jose Massón=/ [fn:migragca].

** gcoop crece y se muda...

Luego de la primera sede en /Almagro/ por la /Av. Corrientes/, nos
mudamos al barrio de /Villa Crespo/ y empezamos a crecer, primero en la
calle /Luis María Drago/, luego en /Juan Ramirez De Velasco/ y mas tarde
en /Julián Alvarez/ para luego ir a /La Pampa/ en /Villa Urquiza/, dicho
de otra manera, pasamos de un monoambiente, a un tres ambientes, luego a
un tres ambientes con terraza, después a una casona de 4 ambientes, mas
dos ambientes extra, donde uno se convirtió en datacenter y otro en
hacklab, para finalmente mudarnos a una oficina gigante de 2 pisos!

** gestión para cooperativas

Como toda empresa, es necesario un software de gestión contable, y de
ser posible, mucho mejor es un /=ERP=/ [fn:erp] /=Enterprise Resource
Planning=/, pero vimos que no había un sistema específico para
cooperativas de trabajo, asi que decidimos desarrollarlo!

Luego de varios intentos en diferentes plataformas, logramos consolidar
nuestro conocimiento y experiencia en =tryton= [fn:tryton], que además
de ser nuestro /ERP/, en el camino liberamos varios módulos para
diferentes tipos de empresas y junto a otras empresas formamos parte de
la =Tryton Foundation= [fn:foundation].

** /Códigos Cooperativos/

En 2012, realizamos un corto para sintetizar como se entrelazan el
"movimiento del /Software Libre/" y el "movimiento cooperativo", este
corto se llamó =Códigos Cooperativos= [fn:corto] y además de liberarlo,
ganamos el /Concurso de Videos del Congreso Argentino de Cooperativas/.

** liberando la nube

En 2015, tuvimos una oportunidad y montamos una /infraestructura libre/,
en servidores propios, manteniendo la
/=soberanía tecnológica=/ [fn:soberania] (si, acá en /Argentina/) y la
llamamos =nube.coop= [fn:nube], donde además de /hostear/ algunos
desarrollos propios, de clientes y organizaciones de la /=Economía
Social y Solidaria=/ [fn:ess], ofrecemos servicios basados íntegramente
en Software Libre.

** manifestar que estás de acuerdo

En el primer punto de nuestro /=Manifiesto gcoop=/ [fn:manifiesto]
esta muy claro, que vivimos de y para el Software Libre en forma
Cooperativa.

#+BEGIN_QUOTE

Nos juntamos para resolver una necesidad: Proveernos de trabajo. Esto
implica entender que nuestra empresa busca no sólo cumplir con lxs
clientxs, sino también desarrollar los intereses de sus socixs,
colaborar para construir una sociedad más justa y difundir el Software
Libre y el Cooperativismo.

#+END_QUOTE

Luego de mucho debate, construimos de forma colectiva un documento al
que llamamos /=acuerdos gcoop=/ [fn:acuerdos]

#+BEGIN_QUOTE

Nuestras acciones buscan resolver el sustento de les socies de la
cooperativa en el marco de la reproducción ampliada de la vida que se
plantea desde la perspectiva de la Economía Social. Es por eso que
tenemos una serie de temáticas que seguimos de forma cotidiana y que
apoyamos y trabajamos desde distintas acciones.

gcoop, como dicen los principios cooperativos, es una organización
autónoma, independiente, con compromiso con su comunidad y el ambiente y
que busca no discriminar por ningún motivo y es en ese marco que hemos
decidido construir este acuerdo para el cumplimiento de nuestro objetivo
de construir una sociedad justa y solidaria:

#+END_QUOTE

** la salida es colectiva!

Junto a otras empresas fundamos =CAdESoL= [fn:cadesol] /=Cámara
Argentina de Empresas de Software Libre=/, y desde nuestros comienzos
apostamos a fomentar la creación de nuevas cooperativas tecnológicas,
porque siempre pensamos que mejor que una cooperativa de 100 personas,
era contar con 10 cooperativas de 10 personas e intercooperar y luego de
unos años, junto a otras cooperativas fundamos =FACTTIC= [fn:facttic] la
/=Federación Argentina de Coooperativas de Trabajo Tecnología Innovación
y Conocimiento=/

** Cooperativismo y Software Libre

Además de muchísimas charlas técnicas sobre diferentes lenguajes de
programación o sobre utilitarios y aplicaciones, en diferentes eventos,
siempre nos ocupamos de fomentar
/=Cooperativismo y Software Libre=/ [fn:coopysl], porque creemos que el
/Software Libre/ es una herramienta vital para todas las cooperativas.

** cooperativismo en pandemia

La pandemia, como a todo el mundo (si bien pertenecemos a un sector
privilegiado), nos puso "mayores desafíos", tuvimos altas y bajas de
socios y socias, dejar de trabajar presencialmente y comenzar a trabajar
remotamente, nos adaptamos y seguimos creciendo para cumplir con los
compromisos asumidos y seguir especializándonos.

** sobrevivir cada /"crisis"/

Obviamente con el paso de los años, crecer implicó todo un aprendizaje y
pasar por diferentes /"crisis"/ y como en cualquier otra /cooperativa de
trabajo/, cada vez que se fue una persona, fue una /"crisis"/...

En 14 años pasaron 48 personas:

- se fueron  4 fundadores
- se fueron  9 aspirantxs
- se fueron 16 socixs
- volvió 1 socio
- ahora somos 16 socixs (2 fundadores) y 3 aspirantxs
- 29 personas ya no son parte de gcoop

La autogestión no es fácil, implica mucho compromiso y ponerse de
acuerdo y organizarse no es tarea fácil, cuanto más personas, más
difícil, pero es posible y /=luego de 14 años seguimos construyendo
colectivamente y trabajando exclusivamente con Software Libre! :)=/.

** /sigamos construyendo.../

Asi como la idea de formar un cooperativa nació simple y fue
escalando, este /post/ comenzó hoy por la mañana con la simple idea de
escribir una reflexión, pero no es tarea simple resumir 14 años, para
mi /=gcoop es un proyecto de vida=/ y no otro laburo más, entonces no
quiero olvidar a nadie ni tampoco dejar de mencionar diferentes
logros, éxitos y fracasos productos del aprendizaje colectivo, por
esto, este artículo, será la base para documentar y actualizar como
puedo /*vivir del software libre*/, siendo parte de /gcoop/.

** tal vez te interese leer...

- [[file:2013-05-31-gcoop-muchas-mentes-tecnopolis-tv.org][gcoop en /Muchas Mentes/, /TecnópolisTV/]]
- [[file:2012-08-30-gcoop-codigos-cooperativos.org][/códigos cooperativos/]]
- [[file:2012-05-18-en-el-medio-digital-software-libre.org][episodio /Software Libre/ ciclo /En el medio digital/]]
- [[file:2012-02-17-las-cooperativas-construyen-un-mundo-mejor.org][/las cooperativas construyen un mundo mejor/]]

[fn:lugs]       https://es.wikipedia.org/wiki/Grupo_de_usuarios_de_Linux
[fn:libertades] https://es.wikipedia.org/wiki/Software_libre#Las_cuatro_libertades_del_software_libre
[fn:cafelug]    https://es.wikipedia.org/wiki/Anexo:Grupos_de_Usuarios_de_Software_Libre_de_Argentina#CaFeLUG
[fn:cafeconf]   https://es.wikipedia.org/wiki/CafeConf
[fn:jrsl]       https://es.wikipedia.org/wiki/Jornadas_Regionales_de_Software_Libre
[fn:gcoop]      https://www.gcoop.coop/
[fn:crm]        https://es.wikipedia.org/wiki/Customer_relationship_management
[fn:atusu]      https://www.gcoop.coop/sugarcrm-para-centro-de-atencion-usuarios-banco-credicoop
[fn:bccl]       https://www.bancocredicoop.coop/
[fn:gca]        https://www.gcoop.coop/gestion-de-contacto-con-el-asociado-banco-credicoop
[fn:migragca]   https://twitter.com/JoseMasson/status/1219612115708915716
[fn:suitecrm]   https://suitecrm.com/
[fn:manifiesto] https://www.gcoop.coop/manifiesto-gcoop
[fn:acuerdos]   https://www.gcoop.coop/acuerdos-gcoop
[fn:erp]        https://es.wikipedia.org/wiki/Sistema_de_planificación_de_recursos_empresariales
[fn:tryton]     https://www.gcoop.coop/erp
[fn:foundation] https://www.tryton.org/foundation
[fn:corto]      https://www.gcoop.coop/codigos-cooperativos
[fn:soberania]  https://es.wikipedia.org/wiki/Soberanía_Tecnológica
[fn:nube]       https://www.nube.coop/
[fn:ess]        https://es.wikipedia.org/wiki/Economía_social_y_solidaria
[fn:cadesol]    https://cadesol.org.ar/
[fn:facttic]    https://facttic.org.ar/
[fn:coopysl]    https://www.gcoop.coop/COOPySL.pdf

** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/653e0db952bf717edddb76ce1c82da40496f05d3][=2021-02-16 15:33=]] agregar /Vivir del Software Libre/
