#+TITLE:       prose.sh a blog platform for hackers
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2022-07-17 20:01
#+HTML_HEAD:   <meta property="og:title" content="prose.sh a blog platform for hackers" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2022-07-17" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gomez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2022-07-17-prose.sh-a-blog-platform-for-hackers.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


** /HackerNews/

Siempre que tengo un par de minutos libres aprovecho a recorrer el sitio
=HackerNews= [fn:hacker-news] porque siempre pero siempre encuentro algo
novedoso y muchas veces encuentro utilidades que termino incorporando y
este Domingo no fue la excepción!

** =prose.sh=

Al principio pensé /"otro sistema de blog minimalista"/, pero le dí un
par de minutos a =prose.sh= [fn:prose.sh]  y quedé sorprendido, por la
facilidad de publicación, si necesidad de registrarme, el proceso es
extremadamente para un amante de =ssh=, bastó ir a =termux= en mi
/teléfono espía/ y tipear:

#+BEGIN_SRC bash :results none :exports code

ssh new@prose.sh

#+END_SRC

Al ingresar por primera vez ( agregando =new@= ) aparece un menú que
permite ingresar el =username=, en mi caso =osiux=:

#+BEGIN_SRC bash :results none :exports code

   prose.sh

  a blog platform for hackers.

  To get started, enter a username.
  Then create a folder locally (e.g. ~/blog).
  Then write your post in markdown files (e.g. hello-world.md).
  Finally, send your files to us:

  scp ~/blog/*.md prose.sh:/

  Enter a username

  > osiux

#+END_SRC

Luego de presionar /ENTER/ se generó la /URL/
[[https://osiux.prose.sh][https://osiux.prose.sh]] y se visualizaba mi
/llave pública de SSH/ con opciones a administrar mis /posts/ y las
/keys/ o simplemente salir.

#+BEGIN_SRC bash :exports code
   prose.sh

  │ Username: osiux
  │ Blog URL: https://osiux.prose.sh
  │ Public key: ssh-rsa
    OVsyzn4a5UBLsIC0GbRqbwNoyZY+EM/dPMbWgVygAKdKRAQZtr
    Vu0zFUxCYyoU4/F5zX0K0oL0X9pEPGAAfMnh30gWFilpibgXp+/
    vzzzEiee5ts6jAfRoTj7UFvHrdrx4cX7aUgcAgwS6YO0eOuJxTN
    +Ue0tHcrh3NX07gccynQFuL2H6KR0yUXTf/x/Uq4yscTGQ0w==
  │ Joined: 17 Jul 2022

  > Set username
    Manage posts
    Manage keys
    Exit

#+END_SRC

** copiar /posts/ para /postear/

Una vez registrado es necesario ingresar con el usuario registrado, pero
para /publicar posts/ solo basta copiar archivos =.md= (formato
/Markdown/) y listo! Eso es todo, se genera el =.html= en =prose.sh= y
ni bien se copia el archivo se obtiene la /URL/ y además se genera
dinámicamente un =index= del sitio, del /post/:

#+BEGIN_SRC bash :results none :exports code

scp 2022-07-17-prose.sh-a-blog-platform-for-hackers.md prose.sh:

2022-07-17-prose.sh-a-blog-platform-for-hackers.md 100% 2599 10.9KB/s 00:00

https://osiux.prose.sh/2022-07-17-prose.sh-a-blog-platform-for-hackers

#+END_SRC

** borrar usando =/dev/nul=

Ingeniosa manera de eliminar un /post/, usando =/dev/null=

#+BEGIN_SRC bash :results none :exports code

cat /dev/null > 2022-07-17-prose.sh.md
scp 2022-07-17-prose.sh.md prose.sh:

#+END_SRC

** migrando de =.org= a =.md=

Mi /blog/ cambió varias veces de formato pero siempre se mantuvo en
/texto plano/ y si bien hace bastante tiempo que lo escribo en formato
=org-mode= [fn:org-mode] siempre estoy haciendo pruebas a otras
alternativas y por esto si solo se trata de copiar archivos =*.md= tal
vez pueda migrar rápidamente todo mi blog!

En un par de minutos desarrollé =org2prose.sh= (que pronto publicaré)
que me permitió convertir de =.org= a =.md= y luego de visitar
=osiux.prose.sh= [fn:osiux.prose] pude hacer algunos ajustes rápidos
para que se visualice un poco mejor.

Me resultó muy gratificante generar un /mirror/ alternativo en un par de
horas y me cautivó la forma en que se visualiza, no elegí nada de /CSS/
y me dejó reflexionando...

** bonus extra!

Un /feature/ que no esperaba para nada y que era un pendiente, es contar
con /RSS/ [fn:osiux-rss] de todos mis /posts/ =:)= lo cual es demasiado,
al parecer esta poniendo todos los /posts/ completos en el /RSS/ y es
enorme! =:P=

Seguramente estaré atento a las próxima mejoras de =prose.sh= y estaré
compartiendo mis /scripts/!

** Tal vez te interese leer...

- [[file:2021-04-28-gemini-es-para-amantes-del-texto-plano.org][=gemini://= es para amantes del texto plano]]
- [[file:2019-04-21-gitlab-ci-org-mode-publish.org][gitlab-ci org-mode publish]]
- [[file:2018-01-01-reemplazando-orgmode-por-txt-bash-jrnl.org][Reemplazando *Org-mode* por =txt-bash-jrnl=]]
- [[file:2013-02-01-migrando-de-frontweb-a-org-mode.org][Migrando de frontweb a Org-mode]]
- [[file:2011-12-29-orgmode-y-gnuplot.org][orgmode y gnuplot una buena combinación]]

[fn:hacker-news]  https://news.ycombinator.com/
[fn:prose.sh]     https://prose.sh/
[fn:org-mode]     http://orgmode.org/
[fn:osiux.prose]  https://osiux.prose.sh/
[fn:osiux-rss]    https://osiux.prose.sh/rss



** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/05428b3e8f402af9b7652e8fbeaf2b95d32ae589][=2022-07-18 23:09=]] corregir sintaxis en /prose.sh a blog platform for hackers/
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/246ea0cb8a8a1f85e44d6f911523935bd6e7c82d][=2022-07-17 20:10=]] agregar prose.sh a blog platform for hackers
