#+TITLE:       Bienvenido de vuelta /Conectar Igualdad/ - Microsoft y Estado, Asunto Separado
#+AUTHOR:      Osiris Alejandro Gomez
#+EMAIL:       osiux@osiux.com
#+LANGUAGE:    es
#+LINK_HOME:   index.html
#+INCLUDE:     header.org
#+DATE:        2022-01-17 23:00
#+HTML_HEAD:   <meta property="og:title" content="Bienvenido de vuelta /Conectar Igualdad/ - Microsoft y Estado, Asunto Separado" />
#+HTML_HEAD:   <meta property="og:type" content="article" />
#+HTML_HEAD:   <meta property="og:article:published_time" content="2022-01-17" />
#+HTML_HEAD:   <meta property="og:article:author" content="Osiris Alejandro Gomez" />
#+HTML_HEAD:   <meta property="og:url" content="https://osiux.com/2022-01-17-conectar-igualdad-microsoft-y-estado-asunto-separado.html" />
#+HTML_HEAD:   <meta property="og:site_name" content="OSiUX" />
#+HTML_HEAD:   <meta property="og:locale" content="es_AR" />


** Buenas Malas Noticias?

Hace muy poco se anunció que volvía el =Plan Conectar Igualdad= [fn:pci]
y esto a priori fue una gran noticia (luego de que fuera discontinuado),
porque volvía la entrega de /netbooks/ con /Software Libre/ a
estudiantes y docentes de escuelas secundarias públicas. =:)=

Pero esta vez, en lugar de contar exclusivamente con el /Sistema
Operativo Libre/ =Huayra= [fn:huayra] desarrollado por el /Estado
Nacional/, en el pliego de licitación, se detalla la compra de
millones de licencias de productos de /Microsoft/. =:(=

** Viento de Cambio

Si bien, hace 10 años, inicialmente los primeros equipos contaban con
/dual boot/, durante el transcurso del proyecto se logró que el /Sistema
Operativo/ por defecto sea libre y luego se entregaron equipos
exclusivamente con /Huayra/ y esta fue una conquista de miles de
personas que aportaron, contribuyeron y formaron una comunidad alrededor
de /Software y Conocimiento Libre/ para millones de estudiantes.

/Huayra/ no detuvo su desarrollo y continuó todos estos años,
agregando mejoras y funcionalidad y cuenta con la /version 5.0/ para
su descarga [fn:huayra-iso]

** Vía Libre [fn:via-libre]

#+BEGIN_QUOTE

Con el acompañamiento de más de 900 firmas, enviamos una carta al
Ministro de Educación, Lic. Jaime Perczyk y al Gerente General de
Educ.ar S.E. Lic. Rubén Daudía, para que revisen la decisión de incluir
licencias de Microsoft Windows 10 y Office en la licitación del
relanzamiento del programa Conectar Igualdad. 

Tras dos años de atravesar una crisis sin par a raíz de la pandemia de
Covid 19, que los chicos y chicas puedan estudiar con una computadora
especialmente preparada para tal fin es un logro fundamental y
estratégico de inclusión y ejercicio del derecho a la educación. Sin
embargo, en medio de la alegría por el regreso del programa, nos
encontramos con la sorpresa de que la licitación plantea la inclusión
del sistema operativo Windows 10 y del paquete de ofimática Microsoft
Office, un auténtico despropósito en una época en la que el Software
Libre ha probado y demostrado con creces su capacidad de ofrecer
sistemas apropiados, funcionales, respetuosos de derechos y libres para
todas las tareas educativas.

Dotar a las computadoras del Programa Conectar Igualdad con un Sistema
Operativo Privativo como Microsoft Windows da un mensaje altamente
nocivo a nuestros estudiantes: Los pone en posición de consumidores de
tecnología y no de productores de la misma.

Junto a todas las personas y organizaciones que acompañan nuestra carta,
pedimos que se revise esta situación y quedamos a disposición de las
autoridades del Ministerio y de Educ.ar para contribuir en la difusión
de Software Libre para la educación de nuestros niños, niñas y
adolescentes en el marco del programa Conectar Igualdad.

#+END_QUOTE

Compartimos la carta [fn:carta-pci] enviada al Ministro, y agradecemos su difusión.

** Para leer sobre /Huayra/ y /Conectar Igualdad/

- [[file:2013-03-18-huayra-el-dia-que-las-vacas-vuelen.org][Huayra, el día que las vacas vuelen, llegó!]]
- [[file:2013-04-06-huayra-grub-rescue-error-unknown-filesystem.org][huayra grub rescue error unknown filesystem]]
- [[file:2013-06-05-invitacion-presentacion-oficial-huayra.org][Invitación Presentación Oficial Huayra en Tecnopolis]]
- [[file:2013-09-13-huayra-primer-sistema-operativo-libre-de-conectar-igualdad.org][Huayra Primer Sistema Operativo Libre de Conectar Igualdad]]
- [[file:2014-04-25-huayra-2.0.org][Disponible Huayra 2.0]]
- [[file:2011-10-24-software-libre-en-monte-caseros-y-ubuntu-11.10-en-conectar-igualdad.org][Software Libre y Conectar Igualdad]]
- [[file:2011-11-10-curso-software-libre-y-programacion-conectar-igualdad.org][Curso básico para alumnos sobre software libre y programación]]
- [[file:conectar-igualdad-empaquetando-intel-theft-deterrent-agent.org][Conectar Igualdad, empaquetando Intel Theft Deterrent Agent TDA]]
- [[file:ubuntu-11.10-en-exomate-de-conectar-igualdad.org][Instalando Ubuntu 11.10 en Exomate de Conectar Igualdad]]

[fn:pci]        https://juanamanso.edu.ar/           
[fn:huayra]     https://huayra.educar.gob.ar/        
[fn:huayra-iso] https://huayra.educar.gob.ar/descargas/
[fn:via-libre]  https://www.vialibre.org.ar/bienvenido-de-vuelta-conectar-igualdad-microsoft-y-estado-asunto-separado/
[fn:carta-pci]  https://www.vialibre.org.ar/wp-content/uploads/2022/01/Bienvenido-de-vuelta-Conectar-Igualdad-_-Estado-y-Microsoft-Asunto-Separado-1.pdf


** ChangeLog

  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/bf3a61526ad2a73cecb77a18995f1d63494e3664][=2022-11-13 20:39=]] agregar y actualizar tags OpenGraph
  - [[https://gitlab.com/osiux/osiux.gitlab.io/-/commit/1a30b5b206cd2aa6e439abfda06ababe8c2c78e7][=2022-01-17 23:59=]] agregar /Bienvenido de vuelta Conectar Igualdad - Microsoft y Estado, Asunto Separado/
